apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc  # Replace with a descriptive name for your PVC
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce  # Adjust if needed (e.g., ReadWriteMany for multi-pod access)
  resources:
    requests:
      storage: 2Gi  # Adjust storage size as needed
