apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/f/CC-MP/435_462_833_834_Back-Up-service-using-docker-and-Kubernetes/Scripts"
