apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-task-pv-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/f/CC-MP/435_462_833_834_Back-Up-service-using-docker-and-Kubernetes/Scripts/"
